POST http://localhost:3007/signup 
Content-Type: application/json

{
    "name":"Jeevan",
    "email":"Jeevan@gmail.com",
    "password":"Jeevan02",
    "isActive":true,
    "createdOn":"2023-08-05T10:00:00Z",
    "isEmailVerified":true
}

###
POST http://localhost:3007/login 
Content-Type: application/json

{
    "email":"Jeevan@gmail.com",
    "password":"Jeevan02"
}